version: "3"
name: "football-team-generator"
services:
  football-team-generator-bot:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IS_PRODUCTION=true
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data\
