name: Node.js TypeScript CI

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # You can change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build # Modify this if your build script is different
